version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: ruby
          command: |
            brew install ruby
            brew link --overwrite ruby
      - run:
          name: prepare
          command: |
            sudo gem install cocoapods
            npm install -g nativescript
            tns usage-reporting disable
            tns error-reporting disable
      - run:
          name: first build fails
          shell: /bin/sh
          command: |
            cd demo
            npm run build.plugin
            tns build ios
            echo "PASS"
      - run: 
          name: build pass
          shell: /bin/sh
          command: |
            cd demo
            tns build ios
            echo "PASS"
      - store_artifacts:
          path: /Users/distiller/.npm/_logs

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
