version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      # - run:
      #     name: pre-start simulator
      #     command: xcrun instruments -w "iPhone 6 (10.3.1) [" || true
      #     background: true
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install CocoaPods
          command: pod install --verbose
      - run:
          name: prepare
          command: |
            sudo gem install bundler
            bundle install
            sudo gem install cocoapods
            sudo gem install xcodeproj
            pod setup
            echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
            npm install -g nativescript
            tns usage-reporting disable
            tns error-reporting disable
      - run:
          name: build
          command: |
            #bundle exec sudo gem install CocoaPods
            cd demo && npm run ci.ios.build
      
      

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test