version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: pre-start simulator
          command: echo "WTF"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test