version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      # - run:
      #     name: pre-start simulator
      #     command: xcrun instruments -w "iPhone 6 (10.3.1) [" || true
      #     background: true
      - run:
          name: prepare
          command: |
            npm install -g nativescript
            tns usage-reporting disable
            tns error-reporting disable
      - run:
          name: build
          command: |
            ls
            bundle exec pod install
            cd demo && npm run ci.ios.build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test